// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Icons icons = _Icons._();
  static final _Images images = _Images._();


}

@immutable
final class _Fonts {
  _Fonts._();

  final String dana_bold_ttf = 'assets/fonts/Dana-Bold.ttf';
  final String dana_regular_ttf = 'assets/fonts/Dana-Regular.ttf';

}

@immutable
final class _Icons {
  _Icons._();
  final String arrow = 'assets/icons/arrow.png';
  final String bluepen_png = 'assets/icons/bluepen.png';
  final String hashtagicon_png = 'assets/icons/hashtagicon.png';
  final String home_png = 'assets/icons/home.png';
  final String micicon_png = 'assets/icons/micicon.png';
  final String user_png = 'assets/icons/user.png';
  final String write_png = 'assets/icons/write.png';

  get micicon => null;

  get bluepen => null;

  get hashtagicon => null;

  get write => null;

  get user => null;

  get home => null;
  
  get arrow_png => null;

}

@immutable
final class _Images {
  _Images._();

  final String bot_svg = 'assets/images/bot.svg';
  final String logo_png = 'assets/images/logo.png';
  final String profileavater_png = 'assets/images/profileavater.png';
  final String programming_png = 'assets/images/programming.png';

  get programming => null;

  get logo => null;

  get profileavater => null;

}

